CREATE SCHEMA IF NOT EXISTS `RESERVATION_HOSPITAL` DEFAULT CHARACTER SET utf8 ;
USE `RESERVATION_HOSPITAL` ;

-- -----------------------------------------------------
-- Table `RESERVATION_HOSPITAL`.`HOSPITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_HOSPITAL`.`HOSPITAL` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  `ADDRESS` VARCHAR(100) NULL,
  `IMAGE` VARCHAR(500) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESERVATION_HOSPITAL`.`RESERVATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_HOSPITAL`.`RESERVATION` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `LOCATOR` VARCHAR(45) NULL,
  `PATIENT` INT(19) NULL,
  `DATE` DATE NULL,
  `SHIFT` VARCHAR(45) NULL,
  `HOSPITAL_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RESERVATION_HOSPITAL_idx` (`HOSPITAL_ID` ASC),
  CONSTRAINT `fk_RESERVATION_HOSPITAL`
    FOREIGN KEY (`HOSPITAL_ID`)
    REFERENCES `RESERVATION_HOSPITAL`.`HOSPITAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESERVATION_HOSPITAL`.`SHIFT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_HOSPITAL`.`SHIFT` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `HOSPITAL_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_SHIFT_HOSPITAL1_idx` (`HOSPITAL_ID` ASC),
  CONSTRAINT `fk_SHIFT_HOSPITAL1`
    FOREIGN KEY (`HOSPITAL_ID`)
    REFERENCES `RESERVATION_HOSPITAL`.`HOSPITAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESERVATION_HOSPITAL`.`ROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVATION_HOSPITAL`.`ROOM` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `CAPACITY` INT(19) NULL,
  `NUMBER` INT(19) NULL,
  `HOSPITAL_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ROOM_HOSPITAL1_idx` (`HOSPITAL_ID` ASC),
  CONSTRAINT `fk_ROOM_HOSPITAL1`
    FOREIGN KEY (`HOSPITAL_ID`)
    REFERENCES `RESERVATION_HOSPITAL`.`HOSPITAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
